### ISSUE TITLE
Single Reponsibility Principle

### ISSUE THREAD

**Issue by DerekPeacock** [JoysgitHub/CosmicRangers#1]
Your MyWorld constructor is doing too many things.  Each method should only have a single reponsibility.

This is a major issue and you must refactor by breaking the code into separate methods each of which does one job.

Please see MyWorld in the **derek** branch.

**Comment by joysitnotes** [comment]
-Methods added to handle each elemet.

**Comment by DerekPeacock** [comment]
Well done!
