### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by joysitnotes** [JoysgitHub/CosmicRangers#19]
-Added music loops on top of itself

**Comment by MohammadQasim03** [comment]
So firstly, I have created "Pause" and "Play” button where user can pause or play the background Music. Then I have created a class which is called "Music"  where I have inserted an "Pause" button image in the class then after creating the class I have inserted the button into main page where the game is then I have saved the button into the World then in "Music" class in "Actor" I have inserted GreenfootSound myMusic = New GreenfootSound ( "The file name"): then what I wanted is that music to start playing when the game starts playing which then I sorted the "Boolean Variable " option  and inserted the first turn = true then in  act section. I gave if statement then added MyMusic. playlopbp(); which make the music play until its get stop then I have inserted another act method for Music which was Mouse clicked where then I inserted play button image then I used  else statement and then added pause button as image so after seeing the result if user wants them to play they can click on play button if pause they can pause it. I added an if statement, MyMusic. playlopbp(); which causes the music to play until it is stopped, and then I added another act method for the music that was mouse clicked where I then added a play button image, used an else statement, and added a pause button as an image. As a result, when the user sees the result, they can choose to play or pause the music by clicking the play button.
