### ISSUE TITLE
Blank Lines

### ISSUE THREAD

**Issue by DerekPeacock** [JoysgitHub/CosmicRangers#4]
Your blank lines are largely ok but:-

{    
    You have been inconsistant with the use of blnk lines.
    You do not need a blank line before a closing brace 
}

You do need a blank line to separate one if{} from a second if{}
and a blank line before the start of each if unless it is connected
together with an else.

You do need a blank line before the start of a method, or the start of
the methods comments.

**Comment by joysitnotes** [comment]
-Blank lines removed
